apiVersion: v1
kind: Service
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  selector:
    app: app-one
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8888
      nodePort: 30007

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  labels:
    app: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: wil42/playground:v1
          env:
            - name: MESSAGE
              value: Hello world from app1
          ports:
            - name: http
              containerPort: 8888
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            failureThreshold: 1
            periodSeconds: 10
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
