apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
spec:
  selector:
    app: playground
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8888
      nodePort: 30007

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  labels:
    app: playground
spec:
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v2
          env:
            - name: MESSAGE
              value: Hello world from app1
          ports:
            - name: http
              containerPort: 8888
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            failureThreshold: 1
            periodSeconds: 10
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
